### ISSUE TITLE
package-lock.json neither in repo nor .gitignore

### ISSUE THREAD

**Issue by apjanke** [mauzigoe/matter-for-vscode#14]
The `package-lock.json` file, which is produced by `npm install` or `npm update` etc., is neither checked in to the repo nor included in the `.gitignore` file. That means when building the extension, it shows up as an untracked file.

From a clean repo on the main branch:

```
[matter-for-vscode] $ git status
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
[matter-for-vscode] $ npm install

added 301 packages, and audited 302 packages in 12s

found 0 vulnerabilities
[matter-for-vscode] $ git status
On branch main
Your branch is up to date with 'origin/main'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	package-lock.json

nothing added to commit but untracked files present (use "git add" to track)
[matter-for-vscode] $
```

I suspect it should be one or the other, so you don't have a local file dropping that gets unintentionally committed with other changes.

I think the normal way to do it is to check it in to the repo, so all developers get consistent, reproducible-ish builds using the same versions of all your dependencies, and the git repo has a history of which versions of all your NPM dependencies you were using at a given time, including the indirect dependencies.

**Comment by mauzigoe** [comment]
Yes, this is right.
I had no clue about this package, but now got an understanding about.

**Comment by mauzigoe** [comment]
gonna add to the repo

**Comment by apjanke** [comment]
Looks good to me!
