### ISSUE TITLE
How to run the MATLAB script?

### ISSUE THREAD

**Issue by ThatBenKraft** [mauzigoe/matter-for-vscode#25]
I know this might sound silly but I can't figure out how to actually run a `.m` file I have open. Is there anything in the GUI or is it console-run?

**Comment by mauzigoe** [comment]
When you have installed the extension, you open a matlab-File. Then press "CTRL+SHIFT+P" and the commmand window open. Then you type in, run matlab File. Which matlab terminal is opening depends on your configuration in the extensions setting.

I will write an example on how to use the extension soon.

**Comment by mauzigoe** [comment]
So the Matlab Terminal opens in Windows (forgot to answer that question, sorry)

**Comment by mauzigoe** [comment]
And the Extension isn't supported in Windows RN

**Comment by ThatBenKraft** [comment]
Okay, just waiting for that then I suppose.
