### ISSUE TITLE
Alternate Matlab versions and installation locations

### ISSUE THREAD

**Issue by apjanke** [mauzigoe/matter-for-vscode#9]
Some users might have multiple Matlab versions installed, and need to work with a specific version, or switch between versions for compatibility testing. Those other versions might not be on the `$PATH`, and it might be inconvenient for the user to reconfigure their environment settings to alter that path. Or Matlab might not be installed at a default location or on the path at all.

How about adding support for multiple/alternate Matlab versions, which can be selectable in the extension? Maybe check the default installation location for various versions and load those as a list of alternatives by default, and allow the user to add additional custom Matlab installation locations?

**Comment by mauzigoe** [comment]
Yes I wanted to add adjustable settings. The need for multiple Matlab Version is a good point. The adjustable setting probably comes with the next release. 
Im thinking rn what'd be a could way to maintain the code structure for saving the options (where members can be optional). Do you if a dictionary is enough or are there better way to handle this?

**Comment by apjanke** [comment]
I don't know enough about how VS Code extension persist user-supplied configuration choices to have a great answer here. I'll do some reading if I have some time; I'm interested in this for my own [Octave Hacking VS Code extension](https://marketplace.visualstudio.com/items?itemName=apjanke.octave-hacking) too.

I'd probably say that a dictionary would work, but maybe isn't ideal, becuase IMHO there's no obvious primary key here, and you might want to search through the list of values on different fields. My guess would instead be an array of structs/objects, where the structs have fields like `{Label, MatlabRelease, PathToMatlabRoot, IsUserDefined}` where:

* Label is the name displayed to the VS Code user when selecting which version to use (like in the thing in the right-hand part of the status bar where you select a Python or Perl interpreter/environment for similar extensions for those languages).
* MatlabRelease is like "R2021b" or "R2019b".
* PathToMatlabRoot is the absolute path to the root of the Matlab installation.
* IsUserDefined is a boolean/logical indicating whether this was an installation that the user explicitly supplied, or whether it was one that the extension auto-detected.

I think the hard part here would be that Matlab installations are specific to a particular computer, can change over time, and you'd want to both autodetect all the Matlab instllations that are present in default locations _and_ maintain a list of user-defined custom installation locations. And [VS Code now supports sync](https://code.visualstudio.com/docs/editor/settings-sync) where your extensions and I think the user's configuration options for them between all your VS Code sessions, which could be on different computers and different operating systems. So I think you might want two or three lists of Matlab installations here: a) the Matlab installs that MatTer detected on this run on this particular computer, b) the user-defined Matlab installs for this particular machine, and maybe c) user-defined Matlab installs that apply to multiple machines? And then you'd merge them at run time. So, maybe three variables/fields/config-values/whatever with similarly-structured arrays that are refreshed/updated/synced using different policies.

I think I'm going to go have a look at some of the Python VS Code extensions and see how they deal with multiple environments. Python is similar in that you often have multiple Python installations, and some of them are at the default locations for the official Python installer, and some of them are at other locations for like Anaconda or user-customized installations.

**Comment by mauzigoe** [comment]
As far as I understand, the most part is set in the `package.json` under the key `"contributes"`. So the typing and structuring can adjusted in there. One just has to retrieve the configuration `vscode.workspace.getConfiguration('extensionName')` and apply the corresponding functionality. I think one does not have to manage the configuration via a class or similar.
And if syncing is supported, one doesn't have to do so much, as I thought ( Tried implement via strict typing and other things, but it seemed too bloated :S )

**Comment by apjanke** [comment]
Ah, cool. Give me a day or two to read up on this; I really have no idea what I'm doing here. ;)

**Comment by mauzigoe** [comment]
I have implemented implemented your proposal. Its still WIP, but you can set up multiple Matlab Terminals, each with its own configuration. You have to set it in a in a `settings.json`-File, but you can reach it via Extension Settings.
You can specify the executable path `mandatory), a license path and a logfile path. The configuration is a list of dictionarys, where each dictionary specify a Matlab Terminal.
If you don't specify any configuration, a default Terminal is used ( Matlab Temrinal is just invoked with "matlab" and no path). 

You can test if you want by switching to branch `10-implement-a-functionality-to-use-the-vs-code-settings-interface` or wait for the next release :)

**Comment by apjanke** [comment]
Cool! I'd like to test it. But I kinda don't know what I'm doing here with VS Code. I'm reading the [VS Code Debugging Extensions page](https://code.visualstudio.com/docs/editor/debugging) but can't figure out what I'm doing wrong.

I'm on macOS 10.14, running VS Code version 1.71.0.  I switched to that `10-implement-...` branch, fired up VS Code on my local repo clone folder, selected the "Run and Debug" item in the left-hand toolbar (the "play" icon with a "bug" over it), and clicked the green "play" button at the top of the left-side bar while the dropdown said "Run Extension". That fired up another VS Code window for extension debugging. I selected "Spawn a Matlab Terminal" from the command palette, and got this error:

<img width="443" alt="image" src="https://user-images.githubusercontent.com/2618447/189559423-6189bad3-7dc8-45a0-af59-3815b7b07e29.png">

```
Activating extension 'LeonFrangen.matter-for-vscode' failed: Cannot find module '/Users/janke/repos/matter-for-vscode/out/extension.js' Require stack: - /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js - /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-amd.js - /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-fork.js.
```

There's no `out/` directory under my matter-for-vscode repo clone. Do you know how to make one, with the `extension.js` file in it? Is there a build/compile step I'm missing here?

**Comment by mauzigoe** [comment]
I have not much experience about `mac` and `npm`, but maybe its a problem with npm? Have tried `npm update` in your projects root folder?

**Comment by mauzigoe** [comment]
I have tested it with a fresh repo. I got the same error as you, but it worked for me after using `npm update`.

**Comment by mauzigoe** [comment]
But adding tests for mac in my github actions would be a good idea.

**Comment by mauzigoe** [comment]
cool :)

**Comment by mauzigoe** [comment]
its WIP, so there are some things to fix. But one get an good impression how it is going to be used.

**Comment by apjanke** [comment]
Okay, I think I'm getting somewhere. I stuck this in my settings, right where it brought me when I clicked this "Edit in settings.json" link in the Extensions preferences.

<img width="495" alt="image" src="https://user-images.githubusercontent.com/2618447/189616652-03d6123e-550c-4191-9d61-43dd52b2138f.png">

```

    "setMatlabExecutable": [
        {
            "terminal": "R2019b in /Applications",
            "option": {
                "matlabExecutablePath": "/Applications/MATLAB_R2019b.app/bin/matlab"
            }
        },
        {
            "terminal": "R2021a in /Applications",
            "option": {
                "matlabExecutablePath": "/Applications/MATLAB_R2021a.app/bin/matlab"
            }

        }
    ]
```

Now Matlab won't launch when doing "Spawn Matlab Terminal" and I get this error message:

<img width="473" alt="image" src="https://user-images.githubusercontent.com/2618447/189616939-f46df5fb-2cec-4cb3-b1f3-a6ab4c0c1377.png">

```
The terminal process "/usr/bin/env 'null', '-nodesktop', '-nosplash'" failed to launch (exit code: 127).
```

I'm thinking I don't understand the format/schema this option is supposed to be supplied in. Help me out here?

**Comment by mauzigoe** [comment]
The options retrievable via the vscode API can be seen in the `package.json` under `contributions.configuration.properties`. There I only retrive the option `setMatlabExecutable`. 
To set the option right you can use this configurtion:
```
    "setMatlabExecutable": [
        {   
            "matlabExecutablePath": "/usr/local/bin/matlab"
        }
    ]
```

**Comment by mauzigoe** [comment]
The object u desribed above is derivated from this confugration.

**Comment by mauzigoe** [comment]
nice :)
